### ISSUE TITLE
Why is value={query} necessary?

### ISSUE THREAD

**Issue by tyleri** [the-road-to-learn-react/the-road-to-learn-react#10]
In chapter2, the book says to insert value={query} in this line:
`<input type="text" value={query} onChange={this.onSearchChange} />`

Why is this necessary? The filtering seems to work without it.

**Comment by rwieruch** [comment]
I have to check again the book. Because of the unidirectional data flow in React applications, you need to let flow the data back to its components. You want to keep them as _Controlled Components_ https://facebook.github.io/react/docs/forms.html But I will keep that open to improve the book paragraph on that! Thanks :)

**Comment by rwieruch** [comment]
@tyleri please keep asking, only that way I know which chapters I can improve 👍

**Comment by tyleri** [comment]
Thanks for responding! Feel free to close the issue.

**Comment by robertf224** [comment]
also found this a bit confusing, would love a bit about "unidirectional data flow" here (or maybe a suggestion to look at the forms link at the end of the chapter which ended up clearing some things up), ended up googling things

**Comment by rwieruch** [comment]
I added a whole unidirectional data flow chapter in version 2 which is released now. Thanks for the suggestion!
