### ISSUE TITLE
Explanations about public and build directories

### ISSUE THREAD

**Issue by PierreTurnbull** [the-road-to-learn-react/the-road-to-learn-react#110]
Hello!

I am reading your book in order to learn React. For now, I am trying to understand how my create-react-app folder works.
After doing some researches and testing, there is something that seems misleading to me. On page 10 you write:

```
• public/: The folder holds all your files when building your project for production. Eventually
all your written code in the src/ folder will be bundled into a couple of files when building
your project and placed in the public folder
```
and also, in the exercises part:

```run the npm run build script and verify that a build/ folder was added to your project```

When buildind my project with `npm run build`, everything is built in the `build` folder. But I see nothing new in the `public` directory, nothing else than `favicon.ico`, `index.html` and `manifest.json`. I don't see any script, like the first citation made me think. How comes?
Also, I would like to understand how the scripts are executed since no script is included in `public/index.html`.
My theory is that it is the boilerplate that relates files in `public` with files in `src`, and it also stores a final version of them all in a `build` folder in order to let me dispose of the whole code, in 1 single directory. Am I true, or what am I missing?

**Comment by rwieruch** [comment]
Hey @PierreTurnbull Thanks for mentioning it 👍  I think it was different in the past, but you are right now! There is nothing new added to the public/ folder. But there should be a build folder with the bundled JavaScript files once you have built your project. Am I right? Would you want to open a Pull Request to fix this issue or should I do it? :) Thanks again!

You can find the scripts in the package.json file. This file exists, because the project is a npm project. You can research the `npm init` script for the command line to find out more about it. Afterward, you can add the scripts (start, test, build, foo, bar, ...) to your scripts configuration in this file. In create-react-app, these scripts run webpack under the hood. If you want to get a deeper understanding on how Webpack, npm and React work together, checkout [this guide](https://www.robinwieruch.de/minimal-react-webpack-babel-setup/).

**Comment by PierreTurnbull** [comment]
I will make a pull request in the afternoon. Ty!
