### ISSUE TITLE
Use let instead of var

### ISSUE THREAD

**Issue by DylanDelobel** [the-road-to-learn-react/the-road-to-learn-react#29]
Since you compare ES5 and ES6 what about replace `var` to `let`

Example : https://github.com/rwieruch/the-road-to-learn-react/blob/master/manuscript/chapter3.txt#L73

**Comment by rwieruch** [comment]
@DylanDelobel have a look in here: https://github.com/rwieruch/the-road-to-learn-react/pull/30 Do you think that it is a valid reason or would you argue that it's confusing?

**Comment by DylanDelobel** [comment]
Hi @rwieruch ,

If you use a up-to-date IDE, it will detect JSX and ES6 and will highlight every `var` like a bad practice

Use const look less confusing, at least for me, what about adding a link in Exercices ?

- Read more about [ways to declare varibales](https://medium.com/@asadalikanwal/javascript-es6-var-let-or-const-f54b8f3722e5#.jxe8hdcz2)

**Comment by rwieruch** [comment]
Hi @DylanDelobel Since I head it more often now, I changed `var` to `const` in all ES6 code pieces: https://github.com/rwieruch/the-road-to-learn-react/commit/fd102a4ea71be1cd2ba2f0c2c927e1fe5f6963a3 Thanks for your feedback 👍 

I tried to avoid to link third party articles, because I have no real control over them. They could be taken offline or get out of date.
