### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jzse** [the-road-to-learn-react/the-road-to-learn-react#33]
Hi Robin, just finished the book, thanks for working on this, it was easy to follow and I feel confident in starting a new app from scratch in the coming days. The exercises at the end of each section were very rewarding e.g. implement fontawesome sorting icons with the classnames package.

I wish there was a little more on testing. Maybe another implementation example, say, after a component is refactored. It would help a student implement and update their own future changes. 

Thanks again

**Comment by rwieruch** [comment]
That's great and valuable feedback! Wow, thank you so much for it @jypsum Since I am working on the 3rd. edition at the moment, I will take your points into account. 

It's great to know that people do some of the exercises and that I could add more them. Because as you said, they can be rewarding when you achieve something on your own. I agree with the testing part. I will do my best to improve it 👍 

Thanks again for reaching out. All the best!
