### ISSUE TITLE
Clarification on isSearched() function on pg 41

### ISSUE THREAD

**Issue by mikengu** [the-road-to-learn-react/the-road-to-learn-react#69]
# Slack Discussion

## The Question
I was a bit confused on the significance of the bang operator on the `isSearched()` function, but someone on the slack channel (Han) quickly cleared that up for me. 
The function in question: 
`const isSearched = searchTerm => item =>
!searchTerm || item.title.toLowerCase().includes(searchTerm.toLowerCase());`

## Answer
The `!` is there to ensure that when the `searchbar` is empty it will evaluate to `true` instead of `false`, thus when invoked by this function
`{ this.state.list.filter(isSearched(this.state.searchTerm)).map(item =>`
it will still map through every value even when the `searchbar` is empty. 

Thank you Han for the clarification and Robin for the great book :)

**Comment by rwieruch** [comment]
I wanted to add the explanation to the book, but it seems like `anyString.includes('')` evaluates always to true now. So there wouldn't be any need to add  `!searchTerm ||` for an empty `searchTerm`. 

Did something change about that particular functionality recently? I recall that the  `!searchTerm ||` had to be there because otherwise the displayed list would be an empty list when the searchTerm is an empty string.

**Comment by rwieruch** [comment]
I close this issue for now. Seems to work.
