### ISSUE TITLE
Refer to "test" rather than "it" in Jest example code ?

### ISSUE THREAD

**Issue by shearichard** [the-road-to-learn-react/the-road-to-learn-react#89]
## Overview 
In the "**Snapshot Tests with Jest**" section use is made of the Jest function `it`.

## Background
I wanted to know a bit more about that function and so I went to read the Jest doco. 

It seems that the primary naming of that function is now `test` and so searching / browsing for `it` in the doco isn't productive (http://facebook.github.io/jest/docs/en/api.html#testname-fn)
.
## Suggestion
I wonder whether the relevant sample code should be altered to make use of 'test' rather than 'it' ?

Another option would be to reference the dual names in the text of the book but that seems to me to producing clutter. 

I appreciate there may be other reasons it should be left as it is but I would be happy to submit a PR if it was thought to be a good idea.

**Comment by rwieruch** [comment]
Hello @shearichard Thanks for coming up with this issue! As long as **it** is supported as well, personally I would opt-in to option 2 to give a brief hint (1 - 2 sentences) to the **test** naming. What do you think? Most test's are using describe and it blocks, that's why I wouldn't want to go away from them for now. Did the documentation say something about the reason behind the name **test**? It seems somehow arbitrary. If you agree with option 2, would you want to open up a Pull Request to mention the **test** naming? :)

**Comment by shearichard** [comment]
Hi @rwieruch 

> What do you think?

Yes, I think that approach is fine.

> Did the documentation say something about the reason behind the name test?

Not where I was looking. I guess it's possible that when the change was made it would have been mentioned in the release notes but I didn't read those. I only found out myself because someone I asked happened to know . Neither name is very search friendly which is a shame.

> would you want to open up a Pull Request to mention the test naming?

Yes I would be happy to. I will do it sometime over the weekend.

thanks for your feedback.

**Comment by rwieruch** [comment]
Thanks for your contribution! Looking forward to the PR 👍
