### ISSUE TITLE
Confused about this.setState

### ISSUE THREAD

**Issue by tyleri** [the-road-to-learn-react/the-road-to-learn-react#9]
~~In chapter2, it says "By using `this.setState` you can manipulate the internal component state."~~

~~Where does this.setState come from? I don't see it defined anywhere. Is it built into React?~~

edit: Was able to look it up and read about it [here](https://facebook.github.io/react/docs/react-component.html#setstate). Might be a good idea to link a resource like this in the book?

On the same page, onSearchChange is also defined like this:
`this.onSearchChange = this.onSearchChange.bind(this);`

Is there any reason why onSearchChange isn't directly defined inside the constructor?

**Comment by tyleri** [comment]
Personally, I think this is easier to understand than using bind, but it may be personal preference:
```
  constructor(props) {
    super(props);

    this.state = {
      list,
      query: ''
    };
    this.onSearchChange = event => this.setState({ query: event.target.value });
  }
```

**Comment by tyleri** [comment]
Closing this because I realized that this was actually also used in the Facebook React example page. Sorry for jumping the gun on this before reading further!

**Comment by rwieruch** [comment]
Hi @tyleri Yes I followed the "official" React best practices from the documentation. Your version is alright, but it wouldn't scale very well that way. Imagine you have not 1 but 10 class methods. Then you want to have an overview of the interface for all methods somewhere, but not the whole method. But thanks, I will think about it again and maybe add a paragraph to the book about it. That's why I will open it again to remember it :)

**Comment by tyleri** [comment]
Great explanation! Thank you!

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/69b2a4696435d4114b80616ec17b9e8aa7cbc15b
